PORT=3000

# R2
R2_BUCKET=eaf
R2_PUBLIC_BASE_URL=https://pub-c54ecb6f6021463e95790b49774c4e8c.r2.dev
R2_S3_ENDPOINT=https://70a41e8a2dd0ed2395771e2a48c2a83a.r2.cloudflarestorage.com
R2_ACCESS_KEY_ID=__PREENCHA__
R2_SECRET_ACCESS_KEY=__PREENCHA__
R2_REGION=auto

# CRM
CRM_TOKEN_URL=https://crm-bot-stg.sigaantenado.com.br/crm/bot/api/v1/authorization/service/get-token
CRM_UPLOAD_FROM_URL_TEMPLATE=https://crm-bot-stg.sigaantenado.com.br/crm/bot/api/v1/service/attachment/ticket/{ticketId}/upload-from-url
CRM_UPDATE_FROM_URL_TEMPLATE=https://crm-bot-stg.sigaantenado.com.br/crm/bot/api/v1/service/attachment/ticket/{ticketId}/{attachmentId}/upload-from-url
CRM_USERNAME=__PREENCHA__
CRM_PASSWORD=__PREENCHA__

# Redis
REDIS_URL=redis://redis:6379
REDIS_TTL_DAYS=180

# Segurança/limites
MAX_DOWNLOAD_MB=25
ALLOWED_URL_PROTOCOLS=https,http
